swagger: '2.0'
info:
  version: '1.07'
  title: eOfdClient Web API Swagger specification(2023-06-27)
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/login:
    post:
      tags:
        - Login
      summary: Авторизация
      operationId: Login_Login
      description: 'После авторизации пользователя в каждый запрос необходимо добавить в заголовок Authorization: Bearer $token_value'
      parameters:
        - name: model
          in: body
          schema:
            $ref: '#/definitions/LoginViewModel'
          x-nullable: true
      responses:
        '200':
          description: ''
          schema: {}
          x-nullable: true
  /api/ofddocument:
    get:
      tags:
        - OfdDocument
      summary: Получить список
      operationId: OfdDocument_Get
      parameters:
        - name: requestParams
          description: '{"startRow":0,"endRow":20,"filter":{"doc_date":{"dateFrom":"2019-11-03 00:00:00.000","dateTo":"2020-03-01 23:59:59.999","type":"inRange"}},"sort":[{"colId":"doc_date","sort":"desc"},{"colId":"hsm_docno","sort":"desc"}]}, где           startRow, endRow - записи, dateFrom, dateTo - границы по дате-времени'
          in: query
          required: false
          type: string
          x-nullable: true
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/MtResponseOfOfdDocumentModel'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true
  /api/ofddocument/report:
    get:
      tags:
      - OfdDocument
      summary: Выгрузка чеков
      operationId: OfdDocument_report
      parameters:
      - type: string
        name: requestParams
        in: query
        x-nullable: true
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/OkResult'
        500:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
        400:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/InvalidModelStateResult'
  /api/clickhouse_document/report:
    get:
      tags:
      - ClickhouseDocument
      summary: Выгрузка чеков
      operationId: ClickhouseDocument_report
      parameters:
      - type: string
        name: requestParams
        in: query
        x-nullable: true
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/OkResult'
        500:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
        400:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/InvalidModelStateResult'
  
  /api/clickhouse_document/reportsumbydate:
    get:
      tags:
      - ClickhouseDocument
      summary: Выгрузка чеков (сумма по дате)
      operationId: ClickhouseDocument_reportsumbydate
      parameters:
      - type: string
        name: requestParams
        in: query
        x-nullable: true
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/OkResult'
        500:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
        400:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/InvalidModelStateResult'
  /api/clickhouse_document/reportsumbyworkshift:
    get:
      tags:
      - ClickhouseDocument
      summary: Выгрузка чеков (сумма по смене)
      operationId: ClickhouseDocument_reportsumbyworkshift
      parameters:
      - type: string
        name: requestParams
        in: query
        x-nullable: true
      responses:
        200:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/OkResult'
        500:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
        400:
          x-nullable: true
          description: ''
          schema:
            $ref: '#/definitions/InvalidModelStateResult'
  
  '/api/ofddocument/show/detail':
    get:
      tags:
        - OfdDocument
      summary: Просмотр чека c форматом
      description: ''
      operationId: OfdDocument_show
      parameters:
        - name: doc_date
          in: query
          required: true
          description: 'Дата и время документа(doc_date)'        
          type: string
          format: date
          x-nullable: false
        - name: fn
          description: 'ФН (hsm_fn)'        
          in: query
          required: true
          type: string
          format: string
          x-nullable: false
        - name: fnsno
          description: 'РНМ (fnsno)'        
          required: true
          in: query
          type: string
          format: string
          x-nullable: false
        - name: fp
          description: 'ФПД (fp)'        
          in: query
          required: true
          type: integer
          format: int32
          x-nullable: false
        - name: doc_no
          description: 'ФД (hsm_docno)'        
          in: query
          required: true
          type: integer
          format: int32
          x-nullable: false
        - name: format
          description: 'Битовая маска, где 1 -  PNG, 2 - PDF, 4 - JSON, 8 - Email, 16 - CMC, 32 - СМС (english), 64 - QrCode'        
          in: query
          required: true
          type: integer
          default: 1
          format: int32
          x-nullable: false
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CheckFormatDataModel'
          x-nullable: true
        '400':
          description: ''
          schema:
            $ref: '#/definitions/InvalidModelStateResult'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true
  /api/ofddocument/dict/dockind:
    get:
      tags:
        - OfdDocument
      summary: Словарь DocKind
      operationId: OfdDocument_GetOfdDocumentDocKindDict
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/OfdDocumentDocKindDictModel'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true
  /api/ofddocument/dict/operationtypedict:
    get:
      tags:
        - OfdDocument
      summary: Словарь OperationTypeDict
      operationId: OfdDocument_GetOfdDocumentOperationTypeDict
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            type: array
            items:
              $ref: '#/definitions/SimpleDictModel'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true
  /api/ofdcheck/checkf:
    get:
      tags:
        - OfdCheck
      summary: Получение чека с форматом
      operationId: OfdCheck_checkf
      parameters:
        - name: fd
          in: query
          required: true
          type: integer
          format: int32
          x-nullable: false
        - name: fn
          in: query
          required: true
          type: string
          x-nullable: true
        - name: fp
          in: query
          required: true
          type: integer
          format: int64
          x-nullable: false
        - name: fnsno
          in: query
          required: false
          type: string
          x-nullable: true
        - name: format
          in: query
          required: false
          type: integer
          default: 1
          format: int32
          x-nullable: false
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CheckFormatDataModel'
          x-nullable: true
        '400':
          description: ''
          schema:
            $ref: '#/definitions/InvalidModelStateResult'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true
  /api/ofdkkt:
    get:
      tags:
        - OfdKKT
      summary: Получить список
      operationId: OfdKKT_Get
      parameters:
        - type: string
          name: requestParams
          in: query
          x-nullable: true
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/MtResponseOfOfdKKTModel'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true
  /api/ofdkkt/{id}:
    get:
      tags:
        - OfdKKT
      summary: Получить одну запись
      operationId: OfdKKT_Get2
      parameters:
        - type: integer
          name: id
          in: path
          required: true
          x-nullable: false
          format: int64
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/OfdKKTModel'
          x-nullable: true
        '400':
          description: ''
          schema:
            $ref: '#/definitions/BadRequestResult'
          x-nullable: true
        '404':
          description: ''
          schema:
            $ref: '#/definitions/NotFoundResult'
          x-nullable: true
        '500':
          description: ''
          schema:
            $ref: '#/definitions/MtErrorResponse'
          x-nullable: true          
securityDefinitions: {}
definitions:
  LoginViewModel:
    type: object
    additionalProperties: false
    required:
      - UserName
      - Password
      - RememberMe
    properties:
      UserName:
        type: string
        description: Идентификатор пользователя (BAN)
      Password:
        type: string
        description: Пароль
      RememberMe:
        type: boolean
        description: Запомнить меня
  OkResult:
    type: object
    properties:
      Request:
        description: Gets a HTTP request message for the results.
        $ref: '#/definitions/HttpRequestMessage'
    description: Represents an action result that returns an empty HttpStatusCode.OK response.
    example:
      Request:
        Version:
          Major: 0
          Revision: 5
          Build: 1
          Minor: 6
          MinorRevision: 2
          MajorRevision: 5
        Content:
          Headers: ''
        Headers: ''
        RequestUri: 'http://example.com/aeiou'
        Method:
          Method: Method
        Properties:
          key: ''
  HttpRequestMessage:
    type: object
    properties:
      Version:
        $ref: '#/definitions/Version'
      Content:
        $ref: '#/definitions/HttpContent'
      Method:
        $ref: '#/definitions/HttpMethod'
      RequestUri:
        type: string
        format: uri
      Headers:
        $ref: '#/definitions/HttpRequestHeaders'
      Properties:
        type: object
        additionalProperties: {}
    example:
      Version:
        Major: 0
        Revision: 5
        Build: 1
        Minor: 6
        MinorRevision: 2
        MajorRevision: 5
      Content:
        Headers: ''
      Headers: ''
      RequestUri: 'http://example.com/aeiou'
      Method:
        Method: Method
      Properties:
        key: ''
  Version:
    type: object
    required:
      - Build
      - Major
      - MajorRevision
      - Minor
      - MinorRevision
      - Revision
    properties:
      Major:
        type: integer
        format: int32
      Minor:
        type: integer
        format: int32
      Build:
        type: integer
        format: int32
      Revision:
        type: integer
        format: int32
      MajorRevision:
        type: integer
      MinorRevision:
        type: integer
    example:
      Major: 0
      Revision: 5
      Build: 1
      Minor: 6
      MinorRevision: 2
      MajorRevision: 5
  HttpContent:
    type: object
    properties:
      Headers:
        $ref: '#/definitions/HttpContentHeaders'
    example:
      Headers: ''
  HttpContentHeaders:
    allOf:
      - type: array
        items:
          $ref: '#/definitions/KeyValuePairOfStringAndIEnumerableOfString'
      - {}
  ContentDispositionHeaderValue:
    type: object
    properties:
      DispositionType:
        type: string
      Parameters:
        type: array
        items:
          $ref: '#/definitions/NameValueHeaderValue'
      Name:
        type: string
      FileName:
        type: string
      FileNameStar:
        type: string
      CreationDate:
        type: string
        format: date-time
      ModificationDate:
        type: string
        format: date-time
      ReadDate:
        type: string
        format: date-time
      Size:
        type: integer
        format: int64
  NameValueHeaderValue:
    type: object
    properties:
      Name:
        type: string
      Value:
        type: string
  ContentRangeHeaderValue:
    type: object
    required:
      - HasLength
      - HasRange
    properties:
      Unit:
        type: string
      From:
        type: integer
        format: int64
      To:
        type: integer
        format: int64
      Length:
        type: integer
        format: int64
      HasLength:
        type: boolean
      HasRange:
        type: boolean
  MediaTypeHeaderValue:
    type: object
    properties:
      CharSet:
        type: string
      Parameters:
        type: array
        items:
          $ref: '#/definitions/NameValueHeaderValue'
      MediaType:
        type: string
  KeyValuePairOfStringAndIEnumerableOfString:
    allOf:
      - $ref: '#/definitions/ValueType'
      - {}
  ValueType:
    type: object
  HttpMethod:
    type: object
    properties:
      Method:
        type: string
    example:
      Method: Method
  HttpRequestHeaders:
    allOf:
      - type: array
        items:
          $ref: '#/definitions/KeyValuePairOfStringAndIEnumerableOfString'
      - {}
  MediaTypeWithQualityHeaderValue:
    allOf:
      - $ref: '#/definitions/MediaTypeHeaderValue'
      - {}
  StringWithQualityHeaderValue:
    type: object
    properties:
      Value:
        type: string
      Quality:
        type: number
        format: double
  AuthenticationHeaderValue:
    type: object
    properties:
      Scheme:
        type: string
      Parameter:
        type: string
  NameValueWithParametersHeaderValue:
    allOf:
      - $ref: '#/definitions/NameValueHeaderValue'
      - {}
  EntityTagHeaderValue:
    type: object
    required:
      - IsWeak
    properties:
      Tag:
        type: string
      IsWeak:
        type: boolean
  RangeConditionHeaderValue:
    type: object
    properties:
      Date:
        type: string
        format: date-time
      EntityTag:
        $ref: '#/definitions/EntityTagHeaderValue'
  RangeHeaderValue:
    type: object
    properties:
      Unit:
        type: string
      Ranges:
        type: array
        items:
          $ref: '#/definitions/RangeItemHeaderValue'
  RangeItemHeaderValue:
    type: object
    properties:
      From:
        type: integer
        format: int64
      To:
        type: integer
        format: int64
  TransferCodingWithQualityHeaderValue:
    allOf:
      - $ref: '#/definitions/TransferCodingHeaderValue'
      - {}
  TransferCodingHeaderValue:
    type: object
    properties:
      Value:
        type: string
      Parameters:
        type: array
        items:
          $ref: '#/definitions/NameValueHeaderValue'
  ProductInfoHeaderValue:
    type: object
    properties:
      Product:
        $ref: '#/definitions/ProductHeaderValue'
      Comment:
        type: string
  ProductHeaderValue:
    type: object
    properties:
      Name:
        type: string
      Version:
        type: string
  CacheControlHeaderValue:
    type: object
    required:
      - MaxStale
      - MustRevalidate
      - NoCache
      - NoStore
      - NoTransform
      - OnlyIfCached
      - Private
      - ProxyRevalidate
      - Public
    properties:
      NoCache:
        type: boolean
      NoCacheHeaders:
        type: array
        items:
          type: string
      NoStore:
        type: boolean
      MaxAge:
        type: string
        format: time-span
      SharedMaxAge:
        type: string
        format: time-span
      MaxStale:
        type: boolean
      MaxStaleLimit:
        type: string
        format: time-span
      MinFresh:
        type: string
        format: time-span
      NoTransform:
        type: boolean
      OnlyIfCached:
        type: boolean
      Public:
        type: boolean
      Private:
        type: boolean
      PrivateHeaders:
        type: array
        items:
          type: string
      MustRevalidate:
        type: boolean
      ProxyRevalidate:
        type: boolean
      Extensions:
        type: array
        items:
          $ref: '#/definitions/NameValueHeaderValue'
  ViaHeaderValue:
    type: object
    properties:
      ProtocolName:
        type: string
      ProtocolVersion:
        type: string
      ReceivedBy:
        type: string
      Comment:
        type: string
  WarningHeaderValue:
    type: object
    required:
      - Code
    properties:
      Code:
        type: integer
        format: int32
      Agent:
        type: string
      Text:
        type: string
      Date:
        type: string
        format: date-time
  MtErrorResponse:
    type: object
    properties:
      error_text:
        type: string
      error_field:
        type: string
  RedirectResult:
    type: object
    properties:
      Location:
        type: string
        format: uri
        description: Gets the location at which the content has been created.
      Request:
        description: Gets the request message which led to this result.
        $ref: '#/definitions/HttpRequestMessage'
    description: 'Represents an action result for a <see cref="F:System.Net.HttpStatusCode.Redirect"/>.'
  InvalidModelStateResult:
    type: object
    required:
      - IncludeErrorDetail
    properties:
      ModelState:
        description: Gets the model state to include in the error.
        $ref: '#/definitions/ModelStateDictionary'
      IncludeErrorDetail:
        type: boolean
        description: Gets a value indicating whether the error should include exception messages.
      ContentNegotiator:
        description: Gets the content negotiator to handle content negotiation.
        $ref: '#/definitions/IContentNegotiator'
      Request:
        description: Gets the request message which led to this result.
        $ref: '#/definitions/HttpRequestMessage'
      Formatters:
        type: array
        description: Gets the formatters to use to negotiate and format the content.
        items:
          $ref: '#/definitions/MediaTypeFormatter'
    description: Represents an action result that returns a  response and performs content negotiation on an  based on a .
  ModelStateDictionary:
    type: object
    required:
      - Count
      - IsReadOnly
      - IsValid
    properties:
      Count:
        type: integer
        format: int32
        description: Gets the number of key/value pairs in the collection.
      IsReadOnly:
        type: boolean
        description: Gets a value that indicates whether the collection is read-only.
      IsValid:
        type: boolean
        description: Gets a value that indicates whether this instance of the model-state dictionary is valid.
      Keys:
        type: array
        description: Gets a collection that contains the keys in the dictionary.
        items:
          type: string
      Values:
        type: array
        description: Gets a collection that contains the values in the dictionary.
        items:
          $ref: '#/definitions/ModelState'
      Item:
        $ref: '#/definitions/ModelState'
    description: 'Represents the state of an attempt to bind a posted form to an action method, which includes validation information.'
  ModelState:
    type: object
    properties:
      Value:
        description: Gets a  object that encapsulates the value that was being bound during model binding.
        $ref: '#/definitions/ValueProviderResult'
      Errors:
        description: Gets a  object that contains any errors that occurred during model binding.
        $ref: '#/definitions/ModelErrorCollection'
    description: 'Encapsulates the state of model binding to a property of an action-method argument, or to the argument itself.'
  ValueProviderResult:
    type: object
    properties:
      AttemptedValue:
        type: string
        description: Gets or sets the raw value that is converted to a string for display.
      Culture:
        type: string
        description: Gets or sets the culture.
      RawValue:
        description: Gets or set the raw value that is supplied by the value provider.
    description: 'Represents the result of binding a value (such as from a form post or query string) to an action-method argument property, or to the argument itself.'
  ModelErrorCollection:
    allOf:
      - type: array
        items:
          $ref: '#/definitions/ModelError'
      - {}
    description: Represents a collection of  instances.
  ModelError:
    type: object
    properties:
      Exception:
        description: Gets or sets the exception object.
        $ref: '#/definitions/Exception'
      ErrorMessage:
        type: string
        description: Gets or sets the error message.
    description: Represents an error that occurs during model binding.
  Exception:
    type: object
    properties:
      Message:
        type: string
      InnerException:
        $ref: '#/definitions/Exception'
      StackTrace:
        type: string
      Source:
        type: string
  IContentNegotiator:
    type: object
    description: 'Performs content negotiation.  This is the process of selecting a response writer (formatter) in compliance with header values in the request. '
  MediaTypeFormatter:
    type: object
    properties:
      SupportedMediaTypes:
        type: array
        description: Gets the mutable collection of media types supported bythis .
        items:
          $ref: '#/definitions/MediaTypeHeaderValue'
      SupportedEncodings:
        type: array
        description: Gets the mutable collection of character encodings supported bythis .
        items:
          $ref: '#/definitions/Encoding'
      MediaTypeMappings:
        type: array
        description: Gets the mutable collection of  objects that match HTTP requests to media types.
        items:
          $ref: '#/definitions/MediaTypeMapping'
      RequiredMemberSelector:
        description: Gets or sets the  instance used to determine required members.
        $ref: '#/definitions/IRequiredMemberSelector'
    description: 'Base class to handle serializing and deserializing strongly-typed objects using . '
  Encoding:
    type: object
    required:
      - CodePage
      - IsBrowserDisplay
      - IsBrowserSave
      - IsMailNewsDisplay
      - IsMailNewsSave
      - IsReadOnly
      - IsSingleByte
      - WindowsCodePage
    properties:
      BodyName:
        type: string
      EncodingName:
        type: string
      HeaderName:
        type: string
      WebName:
        type: string
      WindowsCodePage:
        type: integer
        format: int32
      IsBrowserDisplay:
        type: boolean
      IsBrowserSave:
        type: boolean
      IsMailNewsDisplay:
        type: boolean
      IsMailNewsSave:
        type: boolean
      IsSingleByte:
        type: boolean
      EncoderFallback:
        $ref: '#/definitions/EncoderFallback'
      DecoderFallback:
        $ref: '#/definitions/DecoderFallback'
      IsReadOnly:
        type: boolean
      CodePage:
        type: integer
        format: int32
  EncoderFallback:
    type: object
  DecoderFallback:
    type: object
  MediaTypeMapping:
    type: object
    properties:
      MediaType:
        description: 'Gets the  that is associated with  or   instances that have the given characteristics of the  . '
        $ref: '#/definitions/MediaTypeHeaderValue'
    description: 'An abstract base class used to create an association between  or   instances that have certain characteristics  and a specific .  '
  IRequiredMemberSelector:
    type: object
    description: Defines method that determines whether a given member is required on deserialization.
  NotFoundResult:
    type: object
    properties:
      Request:
        description: Gets the request message which led to this result.
        $ref: '#/definitions/HttpRequestMessage'
    description: Represents an action result that returns an empty  response.
  BadRequestResult:
    type: object
    properties:
      Request:
        description: Gets the request message which led to this result.
        $ref: '#/definitions/HttpRequestMessage'
    description: Represents an action result that returns an empty  response.
  MtResponseOfOfdDocumentModel:
    type: object
    required:
      - count
    properties:
      count:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/OfdDocumentModel'
    example:
      data:
        - in_addr: in_addr
          kktno: kktno
          cash_amount: 6
          operation_type: 1
          in_date: '2000-01-23T04:56:07.000+00:00'
          doc_no: 2
          fns_status: fns_status
          fp: 4
          repeat_count: 5
          client_id: 2
          operation_type_name: operation_type_name
          kkt_id: 7
          hsm_error: hsm_error
          receiptDepth: 1
          hsm_fn: hsm_fn
          id: 6
          out_error: out_error
          doc_kind: 9
          kind_name: kind_name
          out_status: 7
          inn: inn
          bank_amount: 7
          kkt_name: kkt_name
          hsm_docno: 1
          doc_workshift: 3
          total_amount: 1
          doc_date: '2000-01-23T04:56:07.000+00:00'
          kkt_address: kkt_address
          fnsno: fnsno
          hsm_status: 5
        - in_addr: in_addr
          kktno: kktno
          cash_amount: 6
          operation_type: 1
          in_date: '2000-01-23T04:56:07.000+00:00'
          doc_no: 2
          fns_status: fns_status
          fp: 4
          repeat_count: 5
          client_id: 2
          operation_type_name: operation_type_name
          kkt_id: 7
          hsm_error: hsm_error
          receiptDepth: 1
          hsm_fn: hsm_fn
          id: 6
          out_error: out_error
          doc_kind: 9
          kind_name: kind_name
          out_status: 7
          inn: inn
          bank_amount: 7
          kkt_name: kkt_name
          hsm_docno: 1
          doc_workshift: 3
          total_amount: 1
          doc_date: '2000-01-23T04:56:07.000+00:00'
          kkt_address: kkt_address
          fnsno: fnsno
          hsm_status: 5
      count: 0
  OfdDocumentModel:
    type: object
    required:
      - bank_amount
      - cash_amount
      - client_id
      - doc_kind
      - doc_no
      - doc_workshift
      - fp
      - hsm_docno
      - hsm_status
      - id
      - kkt_id
      - operation_type
      - out_status
      - receiptDepth
      - repeat_count
      - total_amount
    properties:
      id:
        type: integer
        format: int64
        description: Идентификатор
      inn:
        type: string
        description: ИНН
      fnsno:
        type: string
        description: Рег.№
      kktno:
        type: string
        description: Заводской номер ККТ
      in_addr:
        type: string
        description: Адрес
      in_date:
        type: string
        format: date-time
        description: Дата получения
      hsm_docno:
        type: integer
        format: int32
        description: Док.№
      hsm_status:
        type: integer
        format: int32
        description: HSM
      hsm_error:
        type: string
        description: HSM ошибка
      fns_status:
        type: string
        description: 'ФНС '
      hsm_fn:
        type: string
        description: ФН
      repeat_count:
        type: integer
        format: int32
        description: '#'
      client_id:
        type: integer
        format: int64
        description: Клиент
      out_status:
        type: integer
        format: int32
        description: Статус отправки
      out_error:
        type: string
        description: Текст ошибки
      doc_kind:
        type: integer
        format: int32
        description: Тип документа
      doc_workshift:
        type: integer
        format: int32
        description: Номер Смены
      kind_name:
        type: string
        description: Название типа документа
      doc_date:
        type: string
        format: date-time
        description: Дата
      doc_no:
        type: integer
        format: int32
        description: Номер документа
      fp:
        type: integer
        format: int64
        description: ФП
      kkt_id:
        type: integer
        format: int64
        description: ИД кассы
      total_amount:
        type: integer
        format: int64
        description: Сумма
      receiptDepth:
        type: integer
        format: int32
        description: Количество позиций
      operation_type:
        type: integer
        format: int32
        description: Тип операции
      operation_type_name:
        type: string
        description: Тип операции расшифровка
      cash_amount:
        type: integer
        format: int64
        description: Сумма нал
      bank_amount:
        type: integer
        format: int64
        description: Сумма б.нал
      kkt_address:
        type: string
        description: Адресс кассы
      kkt_name:
        type: string
        description: Название кассы
    example:
      in_addr: in_addr
      kktno: kktno
      cash_amount: 6
      operation_type: 1
      in_date: '2000-01-23T04:56:07.000+00:00'
      doc_no: 2
      fns_status: fns_status
      fp: 4
      repeat_count: 5
      client_id: 2
      operation_type_name: operation_type_name
      kkt_id: 7
      hsm_error: hsm_error
      receiptDepth: 1
      hsm_fn: hsm_fn
      id: 6
      out_error: out_error
      doc_kind: 9
      kind_name: kind_name
      out_status: 7
      inn: inn
      bank_amount: 7
      kkt_name: kkt_name
      hsm_docno: 1
      doc_workshift: 3
      total_amount: 1
      doc_date: '2000-01-23T04:56:07.000+00:00'
      kkt_address: kkt_address
      fnsno: fnsno
      hsm_status: 5
  CheckFormatDataModel:
    type: object
    required:
      - hasResult
    properties:
      hasResult:
        type: boolean
        description: Присутствие данных
      png:
        type: string
        format: byte
        description: PNG(0x01)
        pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
      pdf:
        type: string
        format: byte
        description: PDF(0x02)
        pattern: '^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$'
      json:
        description: JSON(0x04)
      email:
        type: string
        description: email(0x08)
      sms:
        type: string
        description: sms(0x10)
      sms_eng:
        type: string
        description: sms_eng(0x20)
    description: при отсутствии данных выставляется флаг hasResult
    example:
      pdf: pdf
      sms_eng: sms_eng
      png: png
      sms: sms
      hasResult: true
      json: ''
      email: email
  SendCheckModel:
    type: object
    required:
      - client_id
      - doc_id
    properties:
      doc_id:
        type: integer
        format: int64
        description: id чека
      client_id:
        type: integer
        format: int64
        description: id клиента
      email:
        type: string
      phone:
        type: string
    example:
      phone: phone
      doc_id: 0
      client_id: 6
      email: email
  SimpleDictModel:
    type: object
    properties:
      id: {}
      name:
        type: string
    example:
      name: name
      id: ''
  OfdDocumentDocKindDictModel:
    type: object
    required:
      - code
    properties:
      code:
        type: integer
        format: int32
      name:
        type: string
    example:
      code: 0
      name: name
  MtResponseOfOfdKKTModel:
    type: object
    additionalProperties: false
    required:
      - count
    properties:
      count:
        type: integer
        format: int32
      data:
        type: array
        items:
          $ref: '#/definitions/OfdKKTModel'
  OfdKKTModel:
    type: object
    additionalProperties: false
    required:
      - id
      - client_id
      - fn_status
      - shift_open
      - is_renewal
      - rent_id
      - is_rent
      - fn_kind
      - kkt_kind
      - fn_change
      - fn_change_term
    properties:
      id:
        type: integer
        description: Идентификатор
        format: int64
      name:
        type: string
        description: Название
      address:
        type: string
        description: Адрес
      astatus:
        type: string
        description: Статус
      client_id:
        type: integer
        description: ИД клиента
        format: int64
      fn_activate_date:
        type: string
        description: Дата активации
        format: date-time
      fn_status:
        type: integer
        description: Статус ФН
        format: int32
      tplan:
        type: string
        description: Тариф
      tplan_fdate:
        type: string
        description: Оплачено по
        format: date-time
      kktno:
        type: string
        description: ККТ №
      fnsno:
        type: string
        description: ФНС.№
      fn:
        type: string
        description: 'ФН '
      last_check:
        type: string
        description: Последний чек
        format: date-time
      shift_date:
        type: string
        description: Дата смены
        format: date-time
      shift_open:
        type: integer
        description: Смена открыта
        format: int32
      tplan_name:
        type: string
        description: Название тарифа
      next_tplan:
        type: string
        description: Следующий тариф
      next_tplan_name:
        type: string
        description: Название следующего тарифа
      is_renewal:
        type: integer
        description: Признак автопролонгации
        format: int32
      register_date:
        type: string
        description: Дата регистрации
        format: date-time
      rent_id:
        type: integer
        description: Ссылка на арендную кассу
        format: int64
      is_rent:
        type: integer
        description: Флаг ККТ в аренде
        format: int32
      fn_kind:
        type: integer
        description: Модель ФН
        format: int32
      fn_kind_name:
        type: string
        description: Наименование модели ФН
      kkt_kind:
        type: integer
        description: Модель ККТ
        format: int32
      kkt_kind_name:
        type: string
        description: Наименование модели ККТ
      fn_change:
        type: integer
        description: Признак покупки ФН (аренда)
        format: int32
      fn_change_term:
        type: integer
        description: Срок жизни нового ФН
        format: int32
      fn_change_date:
        type: string
        description: Планируемая дата смены ФН
        format: date-time
      fn_used:
        type: integer
        description: Заполненность ФН, в процентах
        format: int32
    
parameters: {}
responses: {}
x-generator: NSwag v11.3.3.0 (NJsonSchema v9.4.3.0)